#!/usr/bin/env python3
"""
build_stories.py — Cluster related published articles into multi-source Stories.

Nothing previously called supabase_store.upsert_story(); the `stories` table
and the /stories/ + /story/[slug]/ pages existed with no writer behind them.
This is that writer.

Two clustering strategies:
- Theme clusters (THEME_SUBCATEGORIES): a fixed set of cross-company debates
  — safety-leadership departures, model welfare, power/grid strain, AGI
  timelines, AI-slop — cluster by subcategory alone, regardless of company,
  because the story is the cross-lab pattern itself, not one company's event.
- Event clusters: everything else clusters by (company, subcategory) — a
  single company's model launch, funding round, etc. evolving over days.

Either way a cluster only qualifies once it has at least MIN_ARTICLES
articles from at least MIN_PUBLISHERS distinct source publishers in the
lookback window. The site's whole premise is multi-source corroboration, so
one outlet's coverage — however much of it — is not a Story.

For a qualifying cluster, one LLM call cross-references claims across the
member articles' own bodies (already-published, already-fact-checked text —
never external content) and reports, per claim, exactly which source
indices state it and which contradict it. `sources` and `companies` are
built deterministically from the articles' own stored metadata, never
generated by the model, so a story can never cite a source that isn't a
real article already on the site. A claim surviving with a number not
present anywhere in the cluster's own text is dropped (quality.ungrounded_numbers),
the same fabrication check summarize_news.py runs on individual articles.

Slugs are stable per cluster key, not per-run: a re-run upserts the same
row (via supabase_store.upsert_story's on_conflict=slug) instead of creating
duplicates, and first_seen is preserved from the existing row. A cluster
whose newest article is no newer than the story's last_updated is skipped
entirely — nothing changed, so there is nothing to re-synthesize.
"""
from __future__ import annotations

import json
import logging
import os
import re
import sys
import time
from collections import defaultdict
from datetime import datetime, timedelta, timezone

import requests
from slugify import slugify

from ingest_store import current_run_id, get_setting, update_run_stats
from llm import call_llm, required_env_var
from prompts import get_prompt, render
from quality import clean_headline, ungrounded_numbers
from supabase_store import TIMEOUT, _headers, _rest, upsert_story

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%SZ",
)
log = logging.getLogger("build_stories")

MODEL_DEFAULT = os.environ.get("SUMMARIZER_MODEL", "gpt-4o-mini")
TEMPERATURE = 0.2

LOOKBACK_DAYS = 14
MIN_ARTICLES = 2
MIN_PUBLISHERS = 2
MAX_CLUSTER_ARTICLES = 12  # newest N per cluster, keeps the prompt bounded
MAX_BODY_CHARS = 2500  # per article, same reasoning
MAX_CLUSTERS_PER_RUN = 20  # cost ceiling for one 4-hourly run

# Cross-company debate threads: cluster by subcategory alone. Title/slug are
# fixed so the URL and headline a reader bookmarks stay stable; only the
# lead and claims are regenerated as coverage evolves.
THEME_SUBCATEGORIES: dict[str, tuple[str, str]] = {
    "safety_leadership_exits": ("safety-exodus", "The Safety Exodus"),
    "model_welfare_ethics": ("model-welfare", "The Model Welfare Debate"),
    "power_infrastructure": ("power-and-grid", "AI's Power and Grid Problem"),
    "agi_timelines": ("agi-countdown", "The AGI Countdown"),
    "content_ecosystem": ("ai-slop-watch", "AI Slop Watch"),
}


def fetch_candidate_articles(days: int) -> list[dict]:
    """Published articles from the lookback window, with the fields
    clustering and synthesis need. Body is used only to cross-reference the
    site's own already-published, already-fact-checked text."""
    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
    resp = requests.get(
        _rest("articles"),
        headers=_headers(),
        params={
            "select": "id,slug,category,title,body,company,secondary_companies,subcategory,published_at,source_publisher,source_url",
            "status": "eq.published",
            "published_at": f"gte.{cutoff}",
            "order": "published_at.desc",
            "limit": 2000,
        },
        timeout=TIMEOUT,
    )
    resp.raise_for_status()
    return resp.json()


def get_existing_story(slug: str) -> dict | None:
    resp = requests.get(
        _rest("stories"),
        headers=_headers(),
        params={"select": "slug,first_seen,last_updated", "slug": f"eq.{slug}", "limit": 1},
        timeout=TIMEOUT,
    )
    resp.raise_for_status()
    rows = resp.json()
    return rows[0] if rows else None


def build_clusters(articles: list[dict]) -> dict[str, list[dict]]:
    """Group articles by cluster key: subcategory alone for theme topics,
    (company, subcategory) otherwise. An article with no company is dropped
    from event clustering — there's no single-company event to anchor it to,
    and it isn't a theme subcategory either."""
    clusters: dict[str, list[dict]] = defaultdict(list)
    for a in articles:
        sub = a.get("subcategory") or "other"
        if sub in THEME_SUBCATEGORIES:
            clusters[f"theme:{sub}"].append(a)
            continue
        company = a.get("company")
        if not company:
            continue
        clusters[f"event:{slugify(company)}:{sub}"].append(a)
    return clusters


def qualifies(members: list[dict]) -> bool:
    if len(members) < MIN_ARTICLES:
        return False
    publishers = {m.get("source_publisher") for m in members if m.get("source_publisher")}
    return len(publishers) >= MIN_PUBLISHERS


def cluster_identity(key: str, members: list[dict]) -> tuple[str, str | None]:
    """(slug, fixed_title_or_None) for a cluster key."""
    if key.startswith("theme:"):
        sub = key.split(":", 1)[1]
        slug, title = THEME_SUBCATEGORIES[sub]
        return slug, title
    _, company_slug, sub = key.split(":", 2)
    return f"{company_slug}-{sub.replace('_', '-')}", None


def cluster_companies(members: list[dict]) -> list[str]:
    names: set[str] = set()
    for m in members:
        if m.get("company"):
            names.add(m["company"])
        for c in m.get("secondary_companies") or []:
            if c:
                names.add(c)
    return sorted(names)


def cluster_sources(members: list[dict]) -> list[dict]:
    return [
        {
            "title": m.get("title", ""),
            "url": m.get("source_url", ""),
            "publisher": m.get("source_publisher", ""),
            "date": m.get("published_at", ""),
        }
        for m in members
    ]


def _parse_json_object(raw: str) -> dict:
    raw = (raw or "").strip()
    if raw.startswith("```"):
        raw = re.sub(r"^```(?:json)?\s*|\s*```$", "", raw).strip()
    parsed = json.loads(raw)
    if not isinstance(parsed, dict):
        raise ValueError("expected a JSON object")
    return parsed


def process_claims(raw_claims: list, num_members: int, all_source_text: str, cluster_key: str = "") -> list[dict]:
    """Validate and classify the model's raw claim list into storable rows.

    Pure function (no network calls) so this can be exercised directly:
    drops anything not traceable to a real member index, drops any claim
    containing a number absent from the cluster's own source text (the same
    fabrication check summarize_news.py runs per-article), and derives
    status from the support/contradict pattern rather than trusting
    whatever the model itself labeled it.
    """
    claims_out: list[dict] = []
    for claim in raw_claims or []:
        text = str(claim.get("text", "")).strip()
        if not text:
            continue

        bad_numbers = ungrounded_numbers(text, all_source_text)
        if bad_numbers:
            log.warning(
                "dropping claim with ungrounded number(s) %s in %s: %s",
                bad_numbers, cluster_key, text[:80],
            )
            continue

        supporting = sorted({i for i in claim.get("supporting", []) if isinstance(i, int) and 0 <= i < num_members})
        contradicting = sorted({i for i in claim.get("contradicting", []) if isinstance(i, int) and 0 <= i < num_members})
        if not supporting and not contradicting:
            continue  # not traceable to any real source — cannot publish it

        if contradicting:
            status = "disputed"
        elif len(supporting) >= 2:
            status = "corroborated"
        else:
            status = "single_source"

        try:
            confidence = round(min(max(float(claim.get("confidence", 0.5)), 0.0), 1.0), 2)
        except (TypeError, ValueError):
            confidence = 0.5

        claim_row = {
            "text": text,
            "status": status,
            "confidence": confidence,
            "supporting": supporting,
            "contradicting": contradicting,
        }
        note = str(claim.get("note") or "").strip()
        if note:
            claim_row["note"] = note
        claims_out.append(claim_row)

    return claims_out


def compute_trust_score(claims: list[dict]) -> float:
    """Corroborated claims count fully, single-source claims count half,
    disputed claims count zero but still dilute the denominator — a thread
    that's mostly contested facts should score lower than one that's mostly
    independently confirmed, without claiming disagreement itself is bad
    (surfacing it accurately is the product's whole point)."""
    if not claims:
        return 0.0
    corroborated = sum(1 for c in claims if c["status"] == "corroborated")
    single_source = sum(1 for c in claims if c["status"] == "single_source")
    return round((corroborated + 0.5 * single_source) / len(claims), 2)


def synthesize(cluster_key: str, members: list[dict], model: str) -> dict | None:
    """One cross-referencing LLM call over the cluster's own article bodies.

    Returns None if the call/parse fails or no claim survives grounding —
    a story with zero verifiable claims is not worth publishing.
    """
    numbered = [
        f"[{i}] {m.get('source_publisher', 'Unknown')} — {m.get('title', '')} "
        f"({(m.get('published_at') or '')[:10]})\n{(m.get('body') or '')[:MAX_BODY_CHARS]}"
        for i, m in enumerate(members)
    ]

    prompt = render("prompt.story_synthesize.user", count=len(members), articles="\n\n".join(numbered))
    try:
        raw = call_llm(
            model,
            get_prompt("prompt.story_synthesize.system"),
            prompt,
            temperature=TEMPERATURE,
            json_mode=True,
        )
        result = _parse_json_object(raw)
    except Exception as exc:
        log.warning("synthesis failed for %s: %s", cluster_key, exc)
        return None

    all_source_text = "\n".join((m.get("body") or "") for m in members)
    claims_out = process_claims(result.get("claims"), len(members), all_source_text, cluster_key)

    if not claims_out:
        log.info("no verifiable claims survived grounding for %s, skipping", cluster_key)
        return None

    return {
        "title": str(result.get("title", "")).strip(),
        "lead": str(result.get("lead", "")).strip(),
        "claims": claims_out,
        "trust_score": compute_trust_score(claims_out),
    }


def main() -> int:
    model = get_setting("summarizer_model", MODEL_DEFAULT)
    required_key = required_env_var(model)
    if not os.environ.get(required_key):
        log.error("%s not set (required for model %r)", required_key, model)
        return 1

    articles = fetch_candidate_articles(LOOKBACK_DAYS)
    log.info("%d published articles in the last %d days", len(articles), LOOKBACK_DAYS)

    clusters = build_clusters(articles)
    qualifying = {k: v for k, v in clusters.items() if qualifies(v)}
    log.info("%d candidate clusters, %d qualify (>=%d articles, >=%d publishers)",
              len(clusters), len(qualifying), MIN_ARTICLES, MIN_PUBLISHERS)

    # Largest / most active clusters first, in case MAX_CLUSTERS_PER_RUN caps the list.
    ordered = sorted(qualifying.items(), key=lambda kv: len(kv[1]), reverse=True)[:MAX_CLUSTERS_PER_RUN]

    written = 0
    skipped_unchanged = 0
    skipped_no_claims = 0

    for key, members in ordered:
        members = sorted(members, key=lambda m: m.get("published_at") or "", reverse=True)[:MAX_CLUSTER_ARTICLES]
        slug, fixed_title = cluster_identity(key, members)

        newest_published = max((m.get("published_at") or "" for m in members), default="")
        existing = get_existing_story(slug)
        if existing and existing.get("last_updated") and newest_published <= existing["last_updated"]:
            log.debug("no new articles since last run for %s, skipping", slug)
            skipped_unchanged += 1
            continue

        result = synthesize(key, members, model)
        if result is None:
            skipped_no_claims += 1
            continue

        title = fixed_title or clean_headline(result["title"]) or f"{cluster_companies(members)[0]}: {key.split(':', 2)[-1].replace('_', ' ').title()}"
        oldest_published = min((m.get("published_at") or "" for m in members), default=None)
        first_seen = existing["first_seen"] if existing and existing.get("first_seen") else oldest_published

        story_row = {
            "slug": slug,
            "title": title,
            "lead": result["lead"] or None,
            "trust_score": result["trust_score"],
            "companies": cluster_companies(members),
            "sources": cluster_sources(members),
            "claims": result["claims"],
            "first_seen": first_seen,
            "last_updated": datetime.now(timezone.utc).isoformat(),
            "status": "published",
        }

        try:
            upsert_story(story_row)
        except Exception as exc:
            log.warning("could not write story %s: %s", slug, exc)
            continue

        written += 1
        log.info(
            "wrote story /story/%s/ — %d sources, %d claims, trust %.0f%%",
            slug, len(story_row["sources"]), len(story_row["claims"]), story_row["trust_score"] * 100,
        )
        time.sleep(0.3)

    log.info(
        "stories: %d written, %d unchanged, %d had no verifiable claims",
        written, skipped_unchanged, skipped_no_claims,
    )
    update_run_stats(
        current_run_id(),
        stories_written=written,
        stories_unchanged=skipped_unchanged,
        stories_no_claims=skipped_no_claims,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
