-- Fix company links.
--
-- 1. Collapse capitalisation variants onto the spelling already stored in
--    companies. Articles tagged 'Nvidia' were invisible on /companies/nvidia/,
--    which resolves to the name 'NVIDIA'.
-- 2. Add rows for organisations that only ever appear as secondary mentions.
--    The Jekyll generator only created pages for primary companies, so these
--    404'd on the old site too.
--
-- Idempotent: re-running changes nothing.

update public.articles set company = 'ByteDance' where company = 'Bytedance';
update public.articles set secondary_companies = array_replace(secondary_companies, 'Bytedance', 'ByteDance') where 'Bytedance' = any(secondary_companies);
update public.articles set company = 'Iren' where company = 'IREN';
update public.articles set secondary_companies = array_replace(secondary_companies, 'IREN', 'Iren') where 'IREN' = any(secondary_companies);
update public.articles set company = 'KIOXIA' where company = 'Kioxia';
update public.articles set secondary_companies = array_replace(secondary_companies, 'Kioxia', 'KIOXIA') where 'Kioxia' = any(secondary_companies);
update public.articles set company = 'KuaiShou' where company = 'Kuaishou';
update public.articles set secondary_companies = array_replace(secondary_companies, 'Kuaishou', 'KuaiShou') where 'Kuaishou' = any(secondary_companies);
update public.articles set company = 'NVIDIA' where company = 'Nvidia';
update public.articles set secondary_companies = array_replace(secondary_companies, 'Nvidia', 'NVIDIA') where 'Nvidia' = any(secondary_companies);

insert into public.companies (slug, name, description)
select v.slug, v.name, v.description
from (values
    ('a16z', 'a16z', 'Turing Wire coverage of a16z: AI news, research summaries, and analysis.'),
    ('a24', 'A24', 'Turing Wire coverage of A24: AI news, research summaries, and analysis.'),
    ('abb', 'ABB', 'Turing Wire coverage of ABB: AI news, research summaries, and analysis.'),
    ('advent', 'Advent', 'Turing Wire coverage of Advent: AI news, research summaries, and analysis.'),
    ('ai-labs', 'AI labs', 'Turing Wire coverage of AI labs: AI news, research summaries, and analysis.'),
    ('andreessen-horowitz', 'Andreessen Horowitz', 'Turing Wire coverage of Andreessen Horowitz: AI news, research summaries, and analysis.'),
    ('andrew-ng', 'Andrew Ng', 'Turing Wire coverage of Andrew Ng: AI news, research summaries, and analysis.'),
    ('ant-financial', 'Ant Financial', 'Turing Wire coverage of Ant Financial: AI news, research summaries, and analysis.'),
    ('apollo', 'Apollo', 'Turing Wire coverage of Apollo: AI news, research summaries, and analysis.'),
    ('applied-materials', 'Applied Materials', 'Turing Wire coverage of Applied Materials: AI news, research summaries, and analysis.'),
    ('arc-institute', 'Arc Institute', 'Turing Wire coverage of Arc Institute: AI news, research summaries, and analysis.'),
    ('astrix', 'Astrix', 'Turing Wire coverage of Astrix: AI news, research summaries, and analysis.'),
    ('asus', 'ASUS', 'Turing Wire coverage of ASUS: AI news, research summaries, and analysis.'),
    ('autodesk', 'Autodesk', 'Turing Wire coverage of Autodesk: AI news, research summaries, and analysis.'),
    ('aws', 'AWS', 'Turing Wire coverage of AWS: AI news, research summaries, and analysis.'),
    ('bain-capital', 'Bain Capital', 'Turing Wire coverage of Bain Capital: AI news, research summaries, and analysis.'),
    ('banks', 'banks', 'Turing Wire coverage of banks: AI news, research summaries, and analysis.'),
    ('basis', 'Basis', 'Turing Wire coverage of Basis: AI news, research summaries, and analysis.'),
    ('bcg', 'BCG', 'Turing Wire coverage of BCG: AI news, research summaries, and analysis.'),
    ('be-networks', 'BE Networks', 'Turing Wire coverage of BE Networks: AI news, research summaries, and analysis.'),
    ('bergen-engines', 'Bergen Engines', 'Turing Wire coverage of Bergen Engines: AI news, research summaries, and analysis.'),
    ('berkshire-hathaway', 'Berkshire Hathaway', 'Turing Wire coverage of Berkshire Hathaway: AI news, research summaries, and analysis.'),
    ('boosteroid', 'Boosteroid', 'Turing Wire coverage of Boosteroid: AI news, research summaries, and analysis.'),
    ('bose', 'Bose', 'Turing Wire coverage of Bose: AI news, research summaries, and analysis.'),
    ('bridgewater', 'Bridgewater', 'Turing Wire coverage of Bridgewater: AI news, research summaries, and analysis.'),
    ('cadence', 'Cadence', 'Turing Wire coverage of Cadence: AI news, research summaries, and analysis.'),
    ('canadian-pension-giant', 'Canadian pension giant', 'Turing Wire coverage of Canadian pension giant: AI news, research summaries, and analysis.'),
    ('capitalg', 'CapitalG', 'Turing Wire coverage of CapitalG: AI news, research summaries, and analysis.'),
    ('carnegie-mellon', 'Carnegie Mellon', 'Turing Wire coverage of Carnegie Mellon: AI news, research summaries, and analysis.'),
    ('chatgpt', 'ChatGPT', 'Turing Wire coverage of ChatGPT: AI news, research summaries, and analysis.'),
    ('claude', 'Claude', 'Turing Wire coverage of Claude: AI news, research summaries, and analysis.'),
    ('claude-code', 'Claude Code', 'Turing Wire coverage of Claude Code: AI news, research summaries, and analysis.'),
    ('clay', 'Clay', 'Turing Wire coverage of Clay: AI news, research summaries, and analysis.'),
    ('codex', 'Codex', 'Turing Wire coverage of Codex: AI news, research summaries, and analysis.'),
    ('cognizant', 'Cognizant', 'Turing Wire coverage of Cognizant: AI news, research summaries, and analysis.'),
    ('comstock', 'Comstock', 'Turing Wire coverage of Comstock: AI news, research summaries, and analysis.'),
    ('cpp-investments', 'CPP Investments', 'Turing Wire coverage of CPP Investments: AI news, research summaries, and analysis.'),
    ('crowdstrike', 'CrowdStrike', 'Turing Wire coverage of CrowdStrike: AI news, research summaries, and analysis.'),
    ('dataseer', 'DataSeer', 'Turing Wire coverage of DataSeer: AI news, research summaries, and analysis.'),
    ('dbt-labs', 'dbt Labs', 'Turing Wire coverage of dbt Labs: AI news, research summaries, and analysis.'),
    ('deephermes', 'DeepHermes', 'Turing Wire coverage of DeepHermes: AI news, research summaries, and analysis.'),
    ('deliveroo', 'Deliveroo', 'Turing Wire coverage of Deliveroo: AI news, research summaries, and analysis.'),
    ('deutsche-telekom', 'Deutsche Telekom', 'Turing Wire coverage of Deutsche Telekom: AI news, research summaries, and analysis.'),
    ('dl-invest-group', 'DL Invest Group', 'Turing Wire coverage of DL Invest Group: AI news, research summaries, and analysis.'),
    ('doubao', 'Doubao', 'Turing Wire coverage of Doubao: AI news, research summaries, and analysis.'),
    ('etoro', 'eToro', 'Turing Wire coverage of eToro: AI news, research summaries, and analysis.'),
    ('evolution-equity-partners', 'Evolution Equity Partners', 'Turing Wire coverage of Evolution Equity Partners: AI news, research summaries, and analysis.'),
    ('exa-labs', 'Exa Labs', 'Turing Wire coverage of Exa Labs: AI news, research summaries, and analysis.'),
    ('experian', 'Experian', 'Turing Wire coverage of Experian: AI news, research summaries, and analysis.'),
    ('ey', 'EY', 'Turing Wire coverage of EY: AI news, research summaries, and analysis.'),
    ('federal-pacific', 'Federal Pacific', 'Turing Wire coverage of Federal Pacific: AI news, research summaries, and analysis.'),
    ('fitbit', 'Fitbit', 'Turing Wire coverage of Fitbit: AI news, research summaries, and analysis.'),
    ('flock', 'Flock', 'Turing Wire coverage of Flock: AI news, research summaries, and analysis.'),
    ('fortune-500', 'Fortune 500', 'Turing Wire coverage of Fortune 500: AI news, research summaries, and analysis.'),
    ('foxconn', 'Foxconn', 'Turing Wire coverage of Foxconn: AI news, research summaries, and analysis.'),
    ('fractile', 'Fractile', 'Turing Wire coverage of Fractile: AI news, research summaries, and analysis.'),
    ('gaijin', 'Gaijin', 'Turing Wire coverage of Gaijin: AI news, research summaries, and analysis.'),
    ('gemini', 'Gemini', 'Turing Wire coverage of Gemini: AI news, research summaries, and analysis.'),
    ('gemma', 'Gemma', 'Turing Wire coverage of Gemma: AI news, research summaries, and analysis.'),
    ('glilot-capital', 'Glilot Capital', 'Turing Wire coverage of Glilot Capital: AI news, research summaries, and analysis.'),
    ('glm', 'GLM', 'Turing Wire coverage of GLM: AI news, research summaries, and analysis.'),
    ('glm-5-2', 'GLM-5.2', 'Turing Wire coverage of GLM-5.2: AI news, research summaries, and analysis.'),
    ('goldman', 'Goldman', 'Turing Wire coverage of Goldman: AI news, research summaries, and analysis.'),
    ('google-ventures', 'Google Ventures', 'Turing Wire coverage of Google Ventures: AI news, research summaries, and analysis.'),
    ('grok', 'Grok', 'Turing Wire coverage of Grok: AI news, research summaries, and analysis.'),
    ('hcltech', 'HCLTech', 'Turing Wire coverage of HCLTech: AI news, research summaries, and analysis.'),
    ('hellman-friedman', 'Hellman & Friedman', 'Turing Wire coverage of Hellman & Friedman: AI news, research summaries, and analysis.'),
    ('high-flyer', 'High-Flyer', 'Turing Wire coverage of High-Flyer: AI news, research summaries, and analysis.'),
    ('honeyhive', 'HoneyHive', 'Turing Wire coverage of HoneyHive: AI news, research summaries, and analysis.'),
    ('hp', 'HP', 'Turing Wire coverage of HP: AI news, research summaries, and analysis.'),
    ('humain', 'HUMAIN', 'Turing Wire coverage of HUMAIN: AI news, research summaries, and analysis.'),
    ('hunyuan', 'Hunyuan', 'Turing Wire coverage of Hunyuan: AI news, research summaries, and analysis.'),
    ('ice', 'ICE', 'Turing Wire coverage of ICE: AI news, research summaries, and analysis.'),
    ('instagram', 'Instagram', 'Turing Wire coverage of Instagram: AI news, research summaries, and analysis.'),
    ('kalshi', 'Kalshi', 'Turing Wire coverage of Kalshi: AI news, research summaries, and analysis.'),
    ('kimi', 'Kimi', 'Turing Wire coverage of Kimi: AI news, research summaries, and analysis.'),
    ('kkr', 'KKR', 'Turing Wire coverage of KKR: AI news, research summaries, and analysis.'),
    ('knowledge-atlas', 'KNOWLEDGE ATLAS', 'Turing Wire coverage of KNOWLEDGE ATLAS: AI news, research summaries, and analysis.'),
    ('kong', 'Kong', 'Turing Wire coverage of Kong: AI news, research summaries, and analysis.'),
    ('kucoin', 'KuCoin', 'Turing Wire coverage of KuCoin: AI news, research summaries, and analysis.'),
    ('lam-research', 'Lam Research', 'Turing Wire coverage of Lam Research: AI news, research summaries, and analysis.'),
    ('lambda', 'Lambda', 'Turing Wire coverage of Lambda: AI news, research summaries, and analysis.'),
    ('lenovo', 'Lenovo', 'Turing Wire coverage of Lenovo: AI news, research summaries, and analysis.'),
    ('lightspeed-partners', 'Lightspeed Partners', 'Turing Wire coverage of Lightspeed Partners: AI news, research summaries, and analysis.'),
    ('lightspeed-venture-partners', 'Lightspeed Venture Partners', 'Turing Wire coverage of Lightspeed Venture Partners: AI news, research summaries, and analysis.'),
    ('m13', 'M13', 'Turing Wire coverage of M13: AI news, research summaries, and analysis.'),
    ('mckinsey', 'McKinsey', 'Turing Wire coverage of McKinsey: AI news, research summaries, and analysis.'),
    ('microsoft-azure', 'Microsoft Azure', 'Turing Wire coverage of Microsoft Azure: AI news, research summaries, and analysis.'),
    ('mignano-law-group', 'Mignano Law Group', 'Turing Wire coverage of Mignano Law Group: AI news, research summaries, and analysis.'),
    ('mimo', 'MiMo', 'Turing Wire coverage of MiMo: AI news, research summaries, and analysis.'),
    ('minimax-w', 'MINIMAX-W', 'Turing Wire coverage of MINIMAX-W: AI news, research summaries, and analysis.'),
    ('mixhalo', 'Mixhalo', 'Turing Wire coverage of Mixhalo: AI news, research summaries, and analysis.'),
    ('moonshot', 'Moonshot', 'Turing Wire coverage of Moonshot: AI news, research summaries, and analysis.'),
    ('motorola', 'Motorola', 'Turing Wire coverage of Motorola: AI news, research summaries, and analysis.'),
    ('msi', 'MSI', 'Turing Wire coverage of MSI: AI news, research summaries, and analysis.'),
    ('neurovia-ai', 'Neurovia AI', 'Turing Wire coverage of Neurovia AI: AI news, research summaries, and analysis.'),
    ('neutradc', 'NeutraDC', 'Turing Wire coverage of NeutraDC: AI news, research summaries, and analysis.'),
    ('nfx', 'NFX', 'Turing Wire coverage of NFX: AI news, research summaries, and analysis.'),
    ('nhs', 'NHS', 'Turing Wire coverage of NHS: AI news, research summaries, and analysis.'),
    ('nova-ai', 'Nova AI', 'Turing Wire coverage of Nova AI: AI news, research summaries, and analysis.'),
    ('oculus', 'Oculus', 'Turing Wire coverage of Oculus: AI news, research summaries, and analysis.'),
    ('oracle-cloud-infrastructure', 'Oracle Cloud Infrastructure', 'Turing Wire coverage of Oracle Cloud Infrastructure: AI news, research summaries, and analysis.'),
    ('oxford', 'Oxford', 'Turing Wire coverage of Oxford: AI news, research summaries, and analysis.'),
    ('plaid', 'Plaid', 'Turing Wire coverage of Plaid: AI news, research summaries, and analysis.'),
    ('presidio', 'Presidio', 'Turing Wire coverage of Presidio: AI news, research summaries, and analysis.'),
    ('prior-labs', 'Prior Labs', 'Turing Wire coverage of Prior Labs: AI news, research summaries, and analysis.'),
    ('qwen', 'Qwen', 'Turing Wire coverage of Qwen: AI news, research summaries, and analysis.'),
    ('qwen3', 'Qwen3', 'Turing Wire coverage of Qwen3: AI news, research summaries, and analysis.'),
    ('reflection', 'Reflection', 'Turing Wire coverage of Reflection: AI news, research summaries, and analysis.'),
    ('reliance', 'Reliance', 'Turing Wire coverage of Reliance: AI news, research summaries, and analysis.'),
    ('replit', 'Replit', 'Turing Wire coverage of Replit: AI news, research summaries, and analysis.'),
    ('roku', 'Roku', 'Turing Wire coverage of Roku: AI news, research summaries, and analysis.'),
    ('secuvy-ai', 'Secuvy AI', 'Turing Wire coverage of Secuvy AI: AI news, research summaries, and analysis.'),
    ('semidynamics', 'Semidynamics', 'Turing Wire coverage of Semidynamics: AI news, research summaries, and analysis.'),
    ('sequoia-capital', 'Sequoia Capital', 'Turing Wire coverage of Sequoia Capital: AI news, research summaries, and analysis.'),
    ('signalfire', 'SignalFire', 'Turing Wire coverage of SignalFire: AI news, research summaries, and analysis.'),
    ('sk-hynix', 'SK Hynix', 'Turing Wire coverage of SK Hynix: AI news, research summaries, and analysis.'),
    ('sk-telecom', 'SK Telecom', 'Turing Wire coverage of SK Telecom: AI news, research summaries, and analysis.'),
    ('slow-ventures', 'Slow Ventures', 'Turing Wire coverage of Slow Ventures: AI news, research summaries, and analysis.'),
    ('spacexai', 'SpaceXAI', 'Turing Wire coverage of SpaceXAI: AI news, research summaries, and analysis.'),
    ('spark-capital', 'Spark Capital', 'Turing Wire coverage of Spark Capital: AI news, research summaries, and analysis.'),
    ('stackai', 'StackAI', 'Turing Wire coverage of StackAI: AI news, research summaries, and analysis.'),
    ('supervised-semantic-differential', 'Supervised Semantic Differential', 'Turing Wire coverage of Supervised Semantic Differential: AI news, research summaries, and analysis.'),
    ('sureel-ai', 'Sureel AI', 'Turing Wire coverage of Sureel AI: AI news, research summaries, and analysis.'),
    ('synopsys', 'Synopsys', 'Turing Wire coverage of Synopsys: AI news, research summaries, and analysis.'),
    ('synthetic', 'Synthetic', 'Turing Wire coverage of Synthetic: AI news, research summaries, and analysis.'),
    ('tenstorrent', 'Tenstorrent', 'Turing Wire coverage of Tenstorrent: AI news, research summaries, and analysis.'),
    ('tesla', 'Tesla', 'Turing Wire coverage of Tesla: AI news, research summaries, and analysis.'),
    ('thinking-machines-lab', 'Thinking Machines Lab', 'Turing Wire coverage of Thinking Machines Lab: AI news, research summaries, and analysis.'),
    ('threads', 'Threads', 'Turing Wire coverage of Threads: AI news, research summaries, and analysis.'),
    ('thrive-capital', 'Thrive Capital', 'Turing Wire coverage of Thrive Capital: AI news, research summaries, and analysis.'),
    ('tiger-global-management', 'Tiger Global Management', 'Turing Wire coverage of Tiger Global Management: AI news, research summaries, and analysis.'),
    ('tiktok', 'TikTok', 'Turing Wire coverage of TikTok: AI news, research summaries, and analysis.'),
    ('tpg', 'TPG', 'Turing Wire coverage of TPG: AI news, research summaries, and analysis.'),
    ('ubs', 'UBS', 'Turing Wire coverage of UBS: AI news, research summaries, and analysis.'),
    ('uc-berkeley', 'UC Berkeley', 'Turing Wire coverage of UC Berkeley: AI news, research summaries, and analysis.'),
    ('uc-berkeley-measuring-hate-speech-corpus', 'UC Berkeley Measuring Hate Speech corpus', 'Turing Wire coverage of UC Berkeley Measuring Hate Speech corpus: AI news, research summaries, and analysis.'),
    ('uc-san-diego', 'UC San Diego', 'Turing Wire coverage of UC San Diego: AI news, research summaries, and analysis.'),
    ('vercel', 'Vercel', 'Turing Wire coverage of Vercel: AI news, research summaries, and analysis.'),
    ('voi', 'Voi', 'Turing Wire coverage of Voi: AI news, research summaries, and analysis.'),
    ('voltus', 'Voltus', 'Turing Wire coverage of Voltus: AI news, research summaries, and analysis.'),
    ('winwire', 'WinWire', 'Turing Wire coverage of WinWire: AI news, research summaries, and analysis.'),
    ('zhipu', 'Zhipu', 'Turing Wire coverage of Zhipu: AI news, research summaries, and analysis.')
) as v(slug, name, description)
where not exists (
  select 1 from public.companies c where c.slug = v.slug or c.name = v.name
);
